server:
  tomcat:
    max-threads: 50
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types: application/json,application/javascript,text/html,text/xml,text/plain,text/css
  port: 8888

#激活配置文件
spring.profiles.active: development

#thymeleaf
spring.thymeleaf:
   cache: false # Enable template caching.
   check-template-location: true # Check that the templates location exists.
   content-type: text/html # Content-Type value.
   enabled: true # Enable MVC Thymeleaf view resolution.
   encoding: UTF-8 # Template encoding.
   mode: LEGACYHTML5 # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
   prefix: "classpath:/pages" # Prefix that gets prepended to view names when building a URL.
   suffix: ".html"  # Suffix that gets appended to view names when building a URL.

spring.http.converters.preferred-json-mapper: fastjson
# 等同logback-spring.xml里面的配置
logging.level.org.apache.ibatis: debug

spring:
  datasource:
    tomcat:
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      min-idle: 5
      initial-size: 5
      max-wait: 30
      max-active: 10
      validationQuery: SELECT 1;
      testOnBorrow: true
      test-while-idle: true
      #url: 数据库连接
      #username: 数据库帐号
      #password: 数据库密码

wx:
  appid: wx64a4064bb6ebcd71
  #secret: 秘钥
  urls:
    auth: 'https://api.weixin.qq.com/sns/jscode2session?appid=${wx.appid}&secret=${wx.secret}&js_code=%s&grant_type=authorization_code'