export default {
    _bill_post_add: '/bill/post/add',
    _bill_post_update: '/bill/post/update',
    _bill_post_delete: '/bill/post/delete',
    _bill_get_page: '/bill/get/page',
    _bill_get_page_v2: '/bill/get/page/v2',
    _bill_get_page_mine: '/bill/get/page/mine',
    _bill_get_item: '/bill/get/item',
    _bill_get_balanceTypes: '/bill/get/balanceTypes',
    _billtag_get_top10: '/billtag/get/top10',
    _billtag_get_top_query: '/billtag/get/top/query',
    _billtag_get_tags: '/billtag/get/tags',
    _billtype_get_all: '/billtype/get/all',
    _familymember_post_add: '/familymember/post/add',
    _familymember_post_update: '/familymember/post/update',
    _familymember_get_all: '/familymember/get/all',
    _familymember_get_first: '/familymember/get/first',
    _familymember_get_item: '/familymember/get/item',
    _familymember_post_changePassword: '/familymember/post/changePassword',
    _login: '/login',
    _login4Wx: '/login4Wx',
    _verifyToken: '/verifyToken',
    _verifyPassword: '/verifyPassword',
    _v2: '/v2',
    _: '/',
    _userlogin_webpc: '/userlogin/webpc'
}